# Generated by Django 4.2.19 on 2025-03-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SupportAPI", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(default=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="can_be_contacted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="can_data_be_shared",
            field=models.BooleanField(default=False),
        ),
    ]
