# Generated by Django 4.2.19 on 2025-04-02 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "SupportAPI",
            "0003_issue_author_project_author_project_name_contributor_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="user_responsible",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
